### ISSUE TITLE
Project Structure for scalability and maintainability

### ISSUE THREAD

**Issue by maiconcarraro** [manuelbieh/react-ssr-setup#16]
Hi Manuel, do you have any suggestion how to structure for scalability and maintainability?

I was reading this article: https://levelup.gitconnected.com/structure-your-react-redux-project-for-scalability-and-maintainability-618ad82e32b7

And I was checking your project structure, you have **shared > store > app > actions/reducer**, sounds different compared to other structures that i saw, I'll have many pages, I was thinking something like this:

src
| src
|-- client
|---- actions
|---- pages
|---- reducers
....

or

src
| src
|-- client
|---- home (page)
|------ actions, reducers (duck pattern)
|---- about (page)
|------ actions, reducers (duck pattern)
....

What is your thoughts? 

And awesome setup, its the stack i was looking for 👍  very nice

**Comment by manuelbieh** [comment]
> And awesome setup, its the stack i was looking for 👍 very nice

Thanks 😊 

The example here in the repository is probably not the very best. In my projects the Redux structure usually looks like this:

![image](https://user-images.githubusercontent.com/239546/43726384-4cd3928e-999f-11e8-9cfe-1029d4472fab.png)

So basically pretty much your second approach with the difference that all my actions and reducers live in the `shared` part of the app instead of in the `client` part, as they can usually be used fully universally both on the client and the server side.
