### ISSUE TITLE
Can u write a guide how to deploy this app on server for correct ssr working (linux server)?

### ISSUE THREAD

**Issue by artem-yakovenko** [manuelbieh/react-ssr-setup#46]

**Comment by manuelbieh** [comment]
Hey, I bet there are dozens of articles on how to use your favorite continuous integration service to deploy your app to your favorite hosting provider. Since I am not an expert on this I might not be the right one to write such an article. 

Maybe these articles may help you with that:
- https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment
- https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04
- https://www.phusionpassenger.com/library/walkthroughs/deploy/nodejs/ownserver/nginx/oss/deploy_app_main.html
- http://handyjs.org/article/the-kick-ass-guide-to-deploying-nodejs-web-apps-in-production
