### ISSUE TITLE
Build Performance Warnings

### ISSUE THREAD

**Issue by acamposruiz** [manuelbieh/react-ssr-setup#78]
In the build npm process output you get two warnings messages from webpack performance issues. This is the full message:
```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  vendor.c2612e40.chunk.js (434 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  bundle (456 KiB)
      vendor.c2612e40.chunk.js
      bundle.77a055c929b7e8b02f25.css
      bundle.6e20225a.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```
I think it could be a performance improvement to resolve this by a new webpack implementation.

**Comment by manuelbieh** [comment]
The number one reason the bundle is so large is because of corejs/stable:

![image](https://user-images.githubusercontent.com/239546/63855314-68fe7380-c99f-11e9-93ea-99c00f467957.png)

You can optimize that if you know what exactly you need as it is [described here](https://github.com/zloirock/core-js#usage)

The other big factors are `react-dom` and `i18next`. If you don't need internationalization, you can remove it from the build and save a few more kilobytes.
