### ISSUE TITLE
Loadable-components

### ISSUE THREAD

**Issue by RomanBON** [manuelbieh/react-ssr-setup#80]
Hi! Thank you so much for this boilerplate!

What do think about [loadable-components](https://github.com/smooth-code/loadable-components)?
It will be so helpful if you integrate this functionality!

Best regards!

**Comment by manuelbieh** [comment]
Have a look at the TODO list:
https://github.com/manuelbieh/react-ssr-setup#todo

I considered using `react-loadable` or `react-universal-component` but decided against that because of the introduction of the native implementation of `React.lazy` that comes without any additional overhead. The only downside for the moment is, that there is no server side support for `React.Suspense` yet.

Feel free to use loadable-components (or any of the other approaches) in your projects but I don't see the necessity to add it to this starter project due to the forseeable release of server side support for `React.lazy` and `React.Suspense`.
