### ISSUE TITLE
Why is `renderToNodeStream` not used for SSR?

### ISSUE THREAD

**Issue by fullofcaffeine** [manuelbieh/react-ssr-setup#93]
Hi!

I see `helmet-react-async` is being used in the `serverRenderer`:

https://github.com/manuelbieh/react-ssr-setup/blob/21e6dfedd82cb721d423562a0390438e8b67a10e/src/server/middleware/serverRenderer.tsx#L7

However, `React.renderToString` - which is blocking - is still being used. Given that `helmet-react-async` does support it, why not use `renderToNodeStream` instead?

**Comment by manuelbieh** [comment]
I don't remember the exact reason but I tried it and ran into several issues. I decided to not spend more time investigating before Suspense gets full server side support, because I do not yet know if `renderToNodeStream` will still be needed then.

Feel free to experiment and create a PR if you get it running!

**Comment by manuelbieh** [comment]
I **think** (not sure though) live reload was broken, which was only one of several issues I had. But that's more than a year ago and I really can't remember anymore.
